import UIKit


//Fibonacci via function where parameter will be random number generated by another function

func Throw () -> Int {
    return Int.random(in: 1...10)
}

let Random = Throw()
print ("Random number is \(Random)")


func fibSeq (numSteps: Int) -> [Int] {
    var sequence = [0, 1]
    if numSteps <= 1 {
        return sequence
    }
    for _ in 0...numSteps {
        let first = sequence[sequence.count - 2]
        let second = sequence.last!
        sequence.append(first + second)
    }
    return sequence
}


print (fibSeq(numSteps: Random))

